### ISSUE TITLE
Rendering Images

### ISSUE THREAD

**Issue by chester256** [ChrisWu1997/PQ-NET#1]
Could you please provide the rendering images in single view reconstruction task or the rendering scripts? Thank you very much.

**Comment by ChrisWu1997** [comment]
We use the ShapeNet rendered images from [http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz](http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz), provided by [3D-R2N2](https://github.com/chrischoy/3D-R2N2/). Since each shape of PartNet has the corresponding ShapeNet ID, we can find its rendered images from the downloaded files.
