### ISSUE TITLE
about improving the resolution of shape

### ISSUE THREAD

**Issue by fredcool7** [ChrisWu1997/PQ-NET#12]
hi, ChairsWu,
             it is a good job. and i have a quesion after reading your paper. in your paper, the resolution of part is up to 64. how about improving the resolution to 128 and so on? Have you tested when you can reach a limit about the resolution？
             thanks, looking forward to your reply.

**Comment by ChrisWu1997** [comment]
Hi! Thanks for taking interest in our work. In the paper, quantitative metrics are calculated under resolution 64, but the visual results mostly come from resolution 256. And yes, increasing resolution does improve the quality, as shown in Table 1 in the paper. I did try resolution 512 but didn't put those results in the paper, because it runs too slow.

As for the limit about the resolution you mentioned, you mean computationally or the quality? Increasing the resolution would increase the computational cost in a cubic manner; and the quality gain from increasing the resolution would become smaller.

**Comment by fredcool7** [comment]
ok, thanks.
I was thinking before, if it’s just a classification task, can it also process high-resolution shapes at the same time without taking up a lot of memory.

**Comment by ChrisWu1997** [comment]
Not likely, since you would have 8 times more points to query if multiplying the resolution by 2. So both the time and memory cost would increase (but of course there's a trade-off between them).

**Comment by CRISZJ** [comment]
> 嗨！感谢您对我们的工作感兴趣。在本文中，定量指标是在分辨率64下计算的，但视觉结果主要来自分辨率256。是的，提高分辨率确实可以提高质量，如本文表1所示。我确实尝试过512号决议，但没有将这些结果提交论文，因为它运行太慢。
> 
> 至于您提到的分辨率极限，是指计算能力还是质量？增加分辨率将以立方方式增加计算成本；并且通过提高分辨率获得的质量收益将变小。

Hello, I also want to ask, if you use 512 resolution, probably how much memory will be occupied

**Comment by CRISZJ** [comment]
> Hi! Thanks for taking interest in our work. In the paper, quantitative metrics are calculated under resolution 64, but the visual results mostly come from resolution 256. And yes, increasing resolution does improve the quality, as shown in Table 1 in the paper. I did try resolution 512 but didn't put those results in the paper, because it runs too slow.
> 
> As for the limit about the resolution you mentioned, you mean computationally or the quality? Increasing the resolution would increase the computational cost in a cubic manner; and the quality gain from increasing the resolution would become smaller.

Hello, I also want to ask, if you use 512 resolution, probably how much memory will be occupied

**Comment by ChrisWu1997** [comment]
Well, I cannot give a specific number, but I think under 512 resolution, it's not possible to process all points in a single forward pass on a typical GPU like Titan X.

**Comment by CRISZJ** [comment]
> Well, I cannot give a specific number, but I think under 512 resolution, it's not possible to process all points in a single forward pass on a typical GPU like Titan X.

thanks for your reply. so, I want to know if the reason for this limitation is due to GPU storage or computing performance?

**Comment by ChrisWu1997** [comment]
I think the limitation is more on the algorithmic side. As I explained above, the number of points to query increases in a cubic manner when increasing the resolution since we use the naive policy to just sample all points in voxel grids.

Of course, if the GPU memory is large enough, it's ok to process all 512^3 points in a single pass; but with limited GPU memory, we have to split all 512^3 points into several batches, process them one by one and finally combine them together.

**Comment by CRISZJ** [comment]
> I think the limitation is more on the algorithmic side. As I explained above, the number of points to query increases in a cubic manner when increasing the resolution since we use the naive policy to just sample all points in voxel grids.
> 
> Of course, if the GPU memory is large enough, it's ok to process all 512^3 points in a single pass; but with limited GPU memory, we have to split all 512^3 points into several batches, process them one by one and finally combine them together.

ok, thanks.
